name: Build and Push Container Images

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  KO_DOCKER_REPO: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Set up ko
      uses: ko-build/setup-ko@v0.7

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for tag generation
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: dummy
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push exdown image
      env:
        PLATFORMS: linux/amd64,linux/arm64
      run: |
        # Generate tags for exdown
        TAGS=""
        for tag in ${{ steps.meta.outputs.tags }}; do
          clean_tag=$(echo "$tag" | sed 's|dummy|exdown|')
          TAGS="${TAGS}${clean_tag},"
        done
        TAGS=${TAGS%,}  # Remove trailing comma
        
        ko build ./cmd/exdown \
          --platform=${PLATFORMS} \
          --tags=${TAGS} \
          --image-label=org.opencontainers.image.description="FastHTTP-based file downloader" \
          --image-label=org.opencontainers.image.vendor="mlmon" \
          --image-label=org.opencontainers.image.source="${{ github.server_url }}/${{ github.repository }}" \
          --image-label=org.opencontainers.image.revision="${{ github.sha }}"

    - name: Build and push exmembers image
      env:
        PLATFORMS: linux/amd64,linux/arm64
      run: |
        # Generate tags for exmembers
        TAGS=""
        for tag in ${{ steps.meta.outputs.tags }}; do
          clean_tag=$(echo "$tag" | sed 's|dummy|exmembers|')
          TAGS="${TAGS}${clean_tag},"
        done
        TAGS=${TAGS%,}  # Remove trailing comma
        
        ko build ./cmd/exmembers \
          --platform=${PLATFORMS} \
          --tags=${TAGS} \
          --image-label=org.opencontainers.image.description="Memberlist-based cluster membership tool" \
          --image-label=org.opencontainers.image.vendor="mlmon" \
          --image-label=org.opencontainers.image.source="${{ github.server_url }}/${{ github.repository }}" \
          --image-label=org.opencontainers.image.revision="${{ github.sha }}"