name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_EXDOWN: ${{ github.repository }}/exdown
  IMAGE_NAME_EXMEMBERS: ${{ github.repository }}/exmembers

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for exdown
      id: meta-exdown
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_EXDOWN }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Extract metadata for exmembers
      id: meta-exmembers
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_EXMEMBERS }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push exdown image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./cmd/exdown/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta-exdown.outputs.tags }}
        labels: |
          ${{ steps.meta-exdown.outputs.labels }}
          org.opencontainers.image.description=FastHTTP-based file downloader
          org.opencontainers.image.vendor=mlmon
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push exmembers image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./cmd/exmembers/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta-exmembers.outputs.tags }}
        labels: |
          ${{ steps.meta-exmembers.outputs.labels }}
          org.opencontainers.image.description=Memberlist-based cluster membership tool
          org.opencontainers.image.vendor=mlmon
        cache-from: type=gha
        cache-to: type=gha,mode=max