name: Build and Push Container Images

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Set up ko
      uses: ko-build/setup-ko@v0.7

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push exdown image
      env:
        KO_DOCKER_REPO: ghcr.io/${{ github.repository }}/exdown
      run: |
        # Build with specific tag to avoid SHA in image name
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          TAG="latest"
        else
          TAG="${{ github.ref_name }}"
        fi
        
        ko build ./cmd/exdown \
          --bare \
          --platform=linux/amd64,linux/arm64 \
          --tags=${TAG} \
          --image-label=org.opencontainers.image.description="FastHTTP-based file downloader" \
          --image-label=org.opencontainers.image.vendor="mlmon" \
          --image-label=org.opencontainers.image.source="${{ github.server_url }}/${{ github.repository }}" \
          --image-label=org.opencontainers.image.revision="${{ github.sha }}"

    - name: Build and push exmembers image  
      env:
        KO_DOCKER_REPO: ghcr.io/${{ github.repository }}/exmembers
      run: |
        # Build with specific tag to avoid SHA in image name
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          TAG="latest"
        else
          TAG="${{ github.ref_name }}"
        fi
        
        ko build ./cmd/exmembers \
          --bare \
          --platform=linux/amd64,linux/arm64 \
          --tags=${TAG} \
          --image-label=org.opencontainers.image.description="Memberlist-based cluster membership tool" \
          --image-label=org.opencontainers.image.vendor="mlmon" \
          --image-label=org.opencontainers.image.source="${{ github.server_url }}/${{ github.repository }}" \
          --image-label=org.opencontainers.image.revision="${{ github.sha }}"